Script started on 2015年03月13日 (週五) 23時38分48秒
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ vim  lab1_B.cpp[8Pcd lab1vim  lab1_B.cpp[8Pcd lab1vi .vimrc[2Pcd lab1vim  lab1_B.cpp[Kvim  lab1_B.cpp[8Pcd lab1vi .vimrccd[Kvi .vimrc[2Pcd lab1vim  lab1_B.cpp[K./lab1_B
Enter an integer: 22
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ exit

Script done on 2015年03月13日 (週五) 23時39分14秒
