Script started on 2015年03月10日 (週二) 17時52分25秒
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ whoami; pwd
F74036069
/home/F74036069/lab1
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ git config -l
user.name=katherine0504
user.email=F74036069@ncku.edu.tw
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/katherine0504/lab1.git
branch.master.remote=origin
branch.master.merge=refs/heads/master
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ git clone https://[K[K[K[K[K[K[K[Khttps://github.com/katherine0504/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ cat lab1.script
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ mv lat[Kb1.script lab1
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ git[K[K[Kgit remote add [K[K[K[K[K[K[K[K[K[K[Kremoe[Kte add origin [K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kcat lab1.sec[K[Kcript
cat: lab1.script: No such file or directory
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ cd lab1.se[Kcript
bash: cd: lab1.script: No such file or directory
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ cd[K[Kcd 
]0;F74036069@2015cpp: ~F74036069@2015cpp:~$ cd lab1.script
bash: cd: lab1.script: No such file or directory
]0;F74036069@2015cpp: ~F74036069@2015cpp:~$ cd lab1.script[K[K[K[K[K[K[K[K1
]0;F74036069@2015cpp: ~/lab1F74036069@2015cpp:~/lab1$ exit
exit

Script done on 2015年03月10日 (週二) 17時58分33秒
